name: Deploy to Firebase on merge
'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install firebase tools
        run: npm install firebase-tools -g

      - name: Install dependencies
        run: cd functions && npm install

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIRESTRIPE_JOJO }}

      - name: Deploy
        run: firebase deploy
