name: Deploy to Firebase on merge
'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: functions/package-lock.json
          cache: "npm"

      - name: Install functions dependencies
        run: cd functions && npm install

      - name: Install firebase tools
        run: npm install firebase-tools -g

      - name: Deploy
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
